AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  maven-image

  Sample SAM Template for maven-image

Resources:
  HelloWorldFunctionSkipBuild:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 04-maven-skip-sam-build
      CodeUri: HelloWorldFunction/target/HelloWorldSkipBuild-1.0.jar
      Handler: helloworld.App::handleRequest
      Runtime: java11
      Timeout: 20
      Architectures:
        - x86_64
      MemorySize: 1024
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    Metadata:
      SkipBuild: True

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunctionSkipBuild.Arn
