AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example of deploying a GraalVM native image via AWS SAM

Resources:
  HelloWorldFunctionCustomJre:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 05-maven-custom-jre
      CodeUri: HelloWorldFunction/
      Handler: helloworld.App::handleRequest
      Runtime: provided.al2
      Timeout: 20
      Architectures:
        - x86_64
      MemorySize: 1024
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    Metadata:
      BuildMethod: makefile

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunctionCustomJre.Arn
